CONTIKI_PROJECT = sender receiver
all: $(CONTIKI_PROJECT)
CONTIKI = ../..
# Contiki 3.0 links the Rime stack (broadcast_open/broadcast_send) only when asked
CONTIKI_WITH_RIME = 1
include $(CONTIKI)/Makefile.include
